name: Publish resume as Github Page

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out your repository using git
        uses: actions/checkout@v2
        
      - name: Extract theme from resume.json
        uses: sergeysova/jq-action@v2
        id: theme
        with:
          cmd: 'jq .meta.theme resume.json -r'

      - name: Export resume.json as HTML and PDF 
        uses: lexbrugman/action-jsonresume-export@master
        with:
          theme: ${{ steps.theme.outputs.value }}
          resume_filepath: resume.json
          output_filepath: docs/index
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
